### ISSUE TITLE
Please consider updating this library for the newest three.js

### ISSUE THREAD

**Issue by dhoff002** [foo123/MOD3#4]
This is an amazing library and needs to be part of three.js, please update this library to work with the newest three.js, r78.  Thank you so much!

Dan

**Comment by foo123** [comment]
Thank you. As a matter of fact this is an update in progress for quite some time now. i had other projects (and work projects) that needed my attention and it left behind.

Is there any chance you would like to take over this project (with some help from me)?
If yes, it would be great as other people seem to want to use this little library.

If not, then i should do the update.  However i cannot povide a timeframe at this moment. 
Please check back to get updated.

**Comment by dhoff002** [comment]
I'm not sure I have the coding ability to take over this project, otherwise I would love to help.  

Dan

**Comment by foo123** [comment]
MOD3 is updated to version 0.5.0, with support for Three,.js r78 and partial support (in progress) for OSG.js, plus some refactoring and optimisations (see readme etc)

Most probably this will be one of the last updates on this project. If anyone wants to take over after i fix the OSG.js support, ket me know through github

Cheers

**Comment by dhoff002** [comment]
Thank you so much!  This is awesome!

**Comment by foo123** [comment]
Note, i'll do one more update for OSG.js support (as per another request that drew my interest) and some other adjustments, so you can check back a couple of days from now for the final update (this works fine for three.js r78 though)
