### ISSUE TITLE
Change the twist axis

### ISSUE THREAD

**Issue by dhoff002** [foo123/MOD3#5]
How do I change the twist axis in three.js.  Thank you so much for updating this.  It is working great so far!  I can only twist along one axis so far.  Amazing work!

Dan

**Comment by foo123** [comment]
Twist modifier has a paremeter `vector` with respect to which the twist is performed.
The default value is the `Y` axis (`[0,1,0]`) To twist to another axis e.g `Z` do sth like this:

```javascript
var twist = new MOD3.Twist();
twist.vector = new MOD3.Vector3([0,0,1]); // Z axis
// rest code
```

Most 3D modifiers (from as3dmod) are very customizable, however some use only a fixed axis. Twist is customizable with respect to which axis to use

**Comment by foo123** [comment]
After further update the relevant code for the Twist modifier is [this](https://github.com/foo123/MOD3/blob/master/src/modifiers/Twist.js#L30)

Note that one can pass the twist vector in the initialisation of the modifier (it is part of the parameters and similar to other modifiers), although the example code given above will continue to work correctly as expected.
